repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: kafka
    chart: bitnami/kafka
    version: 31.1.1
    namespace: kafka
    values:
      - values/values.bitnami-kafka.yaml
