repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: mysql
    chart: bitnami/mysql
    version: 14.0.0
    namespace: mysql
    values:
      - values/values.bitnami-mysql.yaml
