apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: debezium-kafka-connect
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-kafka-connect
  template:
    metadata:
      labels:
        app: debezium-kafka-connect
    spec:
      containers:
        - name: kafka-connect
          image: confluentinc/cp-kafka-connect:7.2.15
          ports:
            - containerPort: 8083
          readinessProbe:
            httpGet:
              port: 8083
              path: /connectors
            initialDelaySeconds: 15
            periodSeconds: 15
          livenessProbe:
            httpGet:
              port: 8083
              path: /connectors
            initialDelaySeconds: 15
            periodSeconds: 15
          env:
            - name: KAFKA_CONNECT_BOOTSTRAP_SERVERS
              value: kafka-broker-headless.kafka.svc.cluster.local:9092
            - name: KAFKA_CONNECT_REST_PORT
              value: "8083"
            - name: GROUP_ID
              value: debezium-connect-group
            - name: ADVERTISED_PORT
              value: "8083"
            - name: CONFIG_STORAGE_TOPIC
              value: debezium-connect-configs
            - name: OFFSET_STORAGE_TOPIC
              value: debezium-connect-offsets
            - name: STATUS_STORAGE_TOPIC
              value: debezium-connect-status
            - name: KEY_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: VALUE_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: REST_ADVERTISED_HOST_NAME
              value: $(MY_POD_IP)
            - name: REPLICATION_FACTOR
              value: "1"
            - name: REST_ADVERTISED_LISTENER
              value: PLAINTEXT://$(MY_POD_IP)
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
